### ISSUE TITLE
Prompt for admin privileges

### ISSUE THREAD

**Issue by acheong08** [0x0XDev/JamWiFi#12]
I am working on a project for MacOS (not on GitHub) but can't figure out how to prompt for admin privileges.

**Comment by acheong08** [comment]
Is there a one-liner to prompt for these privileges?

**Comment by GGAALL98** [comment]
sudo

**Comment by anonymouz4** [comment]
You can’t elevate an existing process without kext, but you can relaunch your own process with extended privileges via AuthorizationExecuteWithPrivileges, but it’s deprecated and Apple advices for PrivilegedHelper instead. This project is open-source anyway, so I don’t really get your question.
