### ISSUE TITLE
Just wondering...

### ISSUE THREAD

**Issue by abiusx** [0x0XDev/JamWiFi#13]
I was just wondering, having iterated through the old source code (original version) if it's possible to hop channels and jam all available wifis (perhaps except a few)? I don't know if hopping channels too frequently is going to damage the hardware or not, but is this even possible?

**Comment by anonymouz4** [comment]
Well, that feature stayed the same. If you select multiple Access Points on different Channels and SSIDs, it will automatically hop between the channels, but there's no "Jam All" feature. No, it won't damage the hardware, but the channel changing takes time, so in the meantime, no disassociation frame will be sent, and it takes longer until it is on the same channel again
