### ISSUE TITLE
MacOS Big Sur

### ISSUE THREAD

**Issue by Spl01ter** [0x0XDev/JamWiFi#15]
I have been testing it on a MacBook Pro 2018 running Big Sur Beta and it seems not to be crashing the computer. No clients are deauthed though.

**Comment by levydanqc** [comment]
I'm using it on Big Sur (not the Beta version) and it seems to work fine, clients are disconnected, but I don't think the handshake is being saved. Anyone know where it is stored ?

**Comment by rahzam1** [comment]
It crashes if you have a computer 2018 and after It crashed for me I read "read me" it says that not working on Mac 2018 and newer'
I've 2020 macOS

**Comment by Spl01ter** [comment]
It doesn't crash anymore on the latest version of MacOS but deauth still doesn't work
