### ISSUE TITLE
Input files linked to your own file system

### ISSUE THREAD

**Issue by pmstani** [0x0XDev/JamWiFi#4]
Hello,

When I try to clone your repo and compile it in Xcode I get the following error:

`error: Build input files cannot be found: '/Users/System/Volumes/Data/Users/Leonard/Documents/GitHub/JamWiFi/JamWiFi/JWClientKiller.swift', '/Users/System/Volumes/Data/Users/Leonard/Documents/GitHub/JamWiFi/JamWiFi/JWTrafficGatherer.swift', '/Users/System/Volumes/Data/Users/Leonard/Documents/GitHub/JamWiFi/JamWiFi/JWClient.swift', '/Users/System/Volumes/Data/Users/Leonard/Documents/GitHub/JamWiFi/JamWiFi/JWListView.swift', '/Users/System/Volumes/Data/Users/Leonard/Documents/GitHub/JamWiFi/JamWiFi/JWAppDelegate.swift' (in target 'JamWiFi' from project 'JamWiFi')`

It seems that for some reason the path linked for these files is absolute and not relative ?

**Comment by pmstani** [comment]
Drag and dropping the folders in the inspector again and deleting the existing references solved it FYI

**Comment by anonymouz4** [comment]
Interesting, that shouldn‘t happen. I‘ll look at it

**Comment by anonymouz4** [comment]
Fixed
