### ISSUE TITLE
Hidden Networks and sorting

### ISSUE THREAD

**Issue by akballow** [0x0XDev/JamWiFi#8]
Hello, thank you for continuing this project. 
If you have the time to continue adding features. could you please fix the sorting so that items can be listed in signal strength or by stations. Finally, could hidden networks be included as well?

Is there a command-line version of starting and stopping this tool? If not, could scheduling be included somehow?

Thanks

**Comment by anonymouz4** [comment]
Great input, yes I might take a look at the sorting and hidden networks. I definitely wont work on any command-line tool tough.

**Comment by anonymouz4** [comment]
eb5eae94e2d2cc95d6bacedde194b7771028a745
