### ISSUE TITLE
Hidden Network Duplicates

### ISSUE THREAD

**Issue by kirilballow** [0x0XDev/JamWiFi#9]
Thanks for adding in the sorting and hidden networks. I do notice a bug that the same hidden network will show up as a duplicate , triplet, etc. every time you scan. I do see the option to group by ESSID, but what about grouping duplicates by BSSID? That might resolve that issue

**Comment by anonymouz4** [comment]
Fixed 243d077d0fd99dc8b389029c37d434e943516c0f

**Comment by anonymouz4** [comment]
Note to the `Group by ESSID`: This option in the settings is just for the scanning process which should only return the strongest network, if multiple with same ssid and different bssid are found. That part is done by an apple framework, not this app and it seems to be broken and not working anyways, so you can ignore it.
